### ISSUE TITLE
有必要把百度全部屏蔽吗

### ISSUE THREAD

**Issue by ilcn** [4lan5/cn.blacklist.hosts#1]
这个表很有帮助，但是把百度全禁了有必要吗

**Comment by 4lan5** [comment]
@ilcn 这个就看个人了，可能有朋友依赖百毒的某些服务，那删掉或者注释点相关的子域名即可；但是也有人是直接百毒相关关键字完全屏蔽的。这个项目是希望尽量全一些，具体使用的时候根据自己的需求修改即可。
